/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package hotelmanagement;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Color;

/**
 *
 * @author doanvanson
 */
public class AddItem extends javax.swing.JFrame {

    /**
     * Creates new form AddItem
     */
    public AddItem() {
    	setTitle("Hotel Management - DVS");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        AddItem = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        lblItemName = new javax.swing.JLabel();
        lblItemName.setFont(new Font("Lucida Grande", Font.PLAIN, 16));
        lblItemPrice = new javax.swing.JLabel();
        lblItemPrice.setFont(new Font("Lucida Grande", Font.PLAIN, 16));
        inputName = new javax.swing.JTextField();
        inputPrice = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();

        //Frame
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddItem.setBackground(new java.awt.Color(255, 204, 204));
        lblAddItem = new JLabel("Add Item");
        lblAddItem.setBackground(Color.WHITE);
        lblAddItem.setForeground(Color.WHITE);
        lblAddItem.setFont(new Font("Lucida Grande", Font.BOLD | Font.ITALIC, 36));

        // lbl Content
        lblItemName.setText("Item Name");

        lblItemPrice.setText("Item Price");

        //Button back
        btnBack.setFont(new Font("Dialog", Font.BOLD, 16)); 
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-go-back-32.png"))); 
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        // Button Add Item
        btnAddItem.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); 
        btnAddItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-basket-64.png"))); 
        btnAddItem.setText("Add Item");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additem_buttonActionPerformed(evt);
            }
        });
        
    

        javax.swing.GroupLayout gl_AddItem = new javax.swing.GroupLayout(AddItem);
        gl_AddItem.setHorizontalGroup(
        	gl_AddItem.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_AddItem.createSequentialGroup()
        			.addContainerGap(241, Short.MAX_VALUE)
        			.addComponent(lblAddItem, GroupLayout.PREFERRED_SIZE, 182, GroupLayout.PREFERRED_SIZE)
        			.addGap(131)
        			.addComponent(btnBack, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE))
        		.addGroup(gl_AddItem.createSequentialGroup()
        			.addGap(235)
        			.addComponent(btnAddItem)
        			.addContainerGap(240, Short.MAX_VALUE))
        		.addGroup(gl_AddItem.createSequentialGroup()
        			.addGap(208)
        			.addGroup(gl_AddItem.createParallelGroup(Alignment.TRAILING)
        				.addComponent(lblItemName)
        				.addComponent(lblItemPrice))
        			.addGap(18)
        			.addGroup(gl_AddItem.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(inputPrice)
        				.addComponent(inputName, GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
        			.addContainerGap(210, Short.MAX_VALUE))
        );
        gl_AddItem.setVerticalGroup(
        	gl_AddItem.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_AddItem.createSequentialGroup()
        			.addGroup(gl_AddItem.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(btnBack, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addGroup(Alignment.LEADING, gl_AddItem.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(lblAddItem, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)))
        			.addGap(18)
        			.addGroup(gl_AddItem.createParallelGroup(Alignment.BASELINE)
        				.addComponent(inputName, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblItemName))
        			.addGap(21)
        			.addGroup(gl_AddItem.createParallelGroup(Alignment.BASELINE)
        				.addComponent(inputPrice, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblItemPrice))
        			.addGap(18)
        			.addComponent(btnAddItem)
        			.addGap(42))
        );
        AddItem.setLayout(gl_AddItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    // ========= Begin Event Click Button ===========
    
    // Event back_buttonActionPerformed
    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        new Restaurant().setVisible(true);
        this.setVisible(false);
    }
    // Event additem_buttonActionPerformed
    private void additem_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        String name, price;
        name = inputName.getText();
        price = inputPrice.getText();
        if(name.equals("") || price.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill the details");
            return;
        }
        
        int l = price.length();
        for(int i = 0; i < l; i++){
            if(price.codePointAt(i) < 48 || price.codePointAt(i) > 57){
                JOptionPane.showMessageDialog(null, "Invalid price");
                return;
            }
        }
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("JDBC:mysql://192.168.64.2:3306/Hotel_Management_System","root","password");
            Statement stmt = con.createStatement();
            stmt.executeUpdate("USE Hotel_Management_System");
            stmt.executeUpdate("INSERT INTO itemRestaurant(itemName, itemPrice) VALUES('" + name + "','" + price + "')");
            JOptionPane.showMessageDialog(null, "Item Added");
            new Restaurant().setVisible(true);
            this.setVisible(false);
        }
        catch(  HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e)
        {
            System.out.println("Esception: " + e);
        }
        
    }

    //========= End Event Click Button ===========
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputPrice;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblItemPrice;
    private javax.swing.JPanel AddItem;
    private JLabel lblAddItem;
    // End of variables declaration
}
