/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package hotelmanagement;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Color;

/**
 *
 * @author doanvanson
 */
public class AddStaff extends javax.swing.JFrame {

    /**
     * Creates new form AddStaff
     */
    public AddStaff() {
    	setTitle("Hotel Management - DVS");
        initComponents();
    }
    private JFrame frame;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddStaff = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblName.setFont(new Font("Lucida Grande", Font.PLAIN, 16));
        lblContactNumber = new javax.swing.JLabel();
        lblContactNumber.setFont(new Font("Lucida Grande", Font.PLAIN, 16));
        lblCodeStaff = new javax.swing.JLabel();
        lblCodeStaff.setFont(new Font("Lucida Grande", Font.PLAIN, 16));
        lblUsername = new javax.swing.JLabel();
        lblUsername.setFont(new Font("Lucida Grande", Font.PLAIN, 16));
        lblPassword = new javax.swing.JLabel();
        lblPassword.setFont(new Font("Lucida Grande", Font.PLAIN, 16));
        lblRole = new javax.swing.JLabel();
        lblRole.setFont(new Font("Lucida Grande", Font.PLAIN, 16));
        inputName = new javax.swing.JTextField();
        inputContact = new javax.swing.JTextField();
        inputCodeStaff = new javax.swing.JTextField();
        inputUsername = new javax.swing.JTextField();
        inputRole = new javax.swing.JTextField();
        btnAddStaff = new javax.swing.JButton();
        inputPassword = new javax.swing.JPasswordField();

        //Frame
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddStaff.setBackground(new java.awt.Color(255, 204, 204));
        lblAddStaff = new JLabel("Add Staff");
        lblAddStaff.setForeground(Color.WHITE);
        lblAddStaff.setBackground(Color.WHITE);
        lblAddStaff.setFont(new Font("Lucida Grande", Font.BOLD | Font.ITALIC, 36));


        // Buton Back
        btnBack.setFont(new Font("Dialog", Font.BOLD, 16)); 
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-go-back-32.png"))); 
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });
        
        // Button Add Staff
        btnAddStaff.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); 
        btnAddStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-name-tag-64.png"))); 
        btnAddStaff.setText("Add Staff");
        btnAddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstaff_buttonActionPerformed(evt);
            }
        });

        // lbl content
        lblName.setText("Name");

        lblContactNumber.setText("Contact Number");

        lblCodeStaff.setText("Code Staff");

        lblUsername.setText("Username");

        lblPassword.setText("Password");

        lblRole.setText("Role");
        
        
        

        javax.swing.GroupLayout gl_AddStaff = new javax.swing.GroupLayout(AddStaff);
        gl_AddStaff.setHorizontalGroup(
        	gl_AddStaff.createParallelGroup(Alignment.TRAILING)
        		.addGroup(gl_AddStaff.createSequentialGroup()
        			.addGap(269)
        			.addGroup(gl_AddStaff.createParallelGroup(Alignment.TRAILING)
        				.addGroup(Alignment.LEADING, gl_AddStaff.createSequentialGroup()
        					.addGap(73)
        					.addComponent(lblAddStaff, GroupLayout.PREFERRED_SIZE, 213, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
        					.addComponent(btnBack, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE))
        				.addGroup(gl_AddStaff.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(gl_AddStaff.createParallelGroup(Alignment.TRAILING)
        						.addComponent(lblRole)
        						.addComponent(lblPassword)
        						.addComponent(lblName)
        						.addComponent(lblContactNumber)
        						.addGroup(gl_AddStaff.createParallelGroup(Alignment.LEADING)
        							.addComponent(lblUsername)
        							.addComponent(lblCodeStaff)))
        					.addGap(52)
        					.addGroup(gl_AddStaff.createParallelGroup(Alignment.LEADING)
        						.addComponent(inputUsername, 173, 173, 173)
        						.addGroup(gl_AddStaff.createParallelGroup(Alignment.TRAILING, false)
        							.addComponent(inputContact, Alignment.LEADING)
        							.addComponent(inputCodeStaff, Alignment.LEADING)
        							.addComponent(inputPassword, Alignment.LEADING)
        							.addComponent(inputRole, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        							.addComponent(inputName, Alignment.LEADING)))
        					.addContainerGap(248, Short.MAX_VALUE))))
        		.addGroup(gl_AddStaff.createSequentialGroup()
        			.addContainerGap(347, Short.MAX_VALUE)
        			.addComponent(btnAddStaff)
        			.addGap(331))
        );
        gl_AddStaff.setVerticalGroup(
        	gl_AddStaff.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_AddStaff.createSequentialGroup()
        			.addGap(17)
        			.addComponent(lblAddStaff, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE)
        			.addGap(27)
        			.addGroup(gl_AddStaff.createParallelGroup(Alignment.BASELINE)
        				.addComponent(inputName, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblName))
        			.addGap(18)
        			.addGroup(gl_AddStaff.createParallelGroup(Alignment.BASELINE)
        				.addComponent(inputContact, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblContactNumber))
        			.addGap(18)
        			.addGroup(gl_AddStaff.createParallelGroup(Alignment.BASELINE)
        				.addComponent(inputCodeStaff, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblCodeStaff))
        			.addGap(27)
        			.addGroup(gl_AddStaff.createParallelGroup(Alignment.BASELINE)
        				.addComponent(inputUsername, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblUsername))
        			.addGap(22)
        			.addGroup(gl_AddStaff.createParallelGroup(Alignment.BASELINE)
        				.addComponent(inputPassword, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblPassword))
        			.addGap(24)
        			.addGroup(gl_AddStaff.createParallelGroup(Alignment.BASELINE)
        				.addComponent(inputRole, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblRole))
        			.addPreferredGap(ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
        			.addComponent(btnAddStaff)
        			.addGap(23))
        		.addGroup(gl_AddStaff.createSequentialGroup()
        			.addComponent(btnBack, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(539, Short.MAX_VALUE))
        );
        AddStaff.setLayout(gl_AddStaff);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>
    
    // ========= Begin Event Click Button ===========
    
    // Event back_buttonActionPerformed
    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        new MainScreen().setVisible(true);
        this.setVisible(false);
    }
    
    // Event addstaff_buttonActionPerformed
    private void addstaff_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        String name, contact, codeStaff, username, password, role;
        name = inputName.getText();
        password = new String(inputPassword.getPassword());
        contact = inputContact.getText();
        codeStaff = inputCodeStaff.getText();;
        username = inputUsername.getText();
        role = inputRole.getText();
        
        if(name.equals("") || password.equals("") || contact.equals("") || codeStaff.equals("") || username.equals("") || role.equals("")){
            JOptionPane.showMessageDialog(frame, "Please fill the details");
            return;
        }
        
        int l = contact.length();
        for(int i = 0; i < l; i++){
        	// PhoneNumber 0 between 9
            if(contact.codePointAt(i) < 48 || contact.codePointAt(i) >57){
                JOptionPane.showMessageDialog(frame, "Invalid Contact Phone Number, input 0 -> 9");
                return;
            }
        }
        
        if(!role.equals("admin") && !role.equals("user")) {
        	JOptionPane.showMessageDialog(frame, "Role is 'admin' or 'user'");
            return;
        }
          
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("JDBC:mysql://192.168.64.2:3306/Hotel_Management_System", "root", "password");
            Statement stmt = con.createStatement();
            stmt.executeUpdate("USE Hotel_Management_System");
            stmt.executeUpdate("INSERT INTO staff(name, contact, codeStaff, username, password, role) VALUES('" + name + "','" + contact + "','" + codeStaff + "','" + username + "','" + password + "','" + role + "')");
            JOptionPane.showMessageDialog(frame, "Staff Added");
            new MainScreen().setVisible(true);
            this.setVisible(false);
        }
        catch(  HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e)
        {
            System.out.println("Esception: " + e);
        }
    }
    //========= End Event Click Button ===========
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnAddStaff;
    private javax.swing.JTextField inputCodeStaff;
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField inputContact;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblCodeStaff;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JPanel AddStaff;
    private javax.swing.JTextField inputName;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JTextField inputRole;
    private JLabel lblAddStaff;
    // End of variables declaration
}
