/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package hotelmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.Font;
import javax.swing.JLabel;
import java.awt.Color;

/**
 *
 * @author doanvanson
 */
public class CustomerList extends javax.swing.JFrame {

    /**
     * Creates new form CustomerList
     */
    public CustomerList() {
    	setTitle("Hotel Management - DVS");
        initComponents();
        showDetails();
    }
    private JFrame frame;
    
    // ======== Begin Get Database Table Room ========== 
    public void showDetails(){
    	DefaultTableModel defaultTableModel = new DefaultTableModel(){
        	@Override
        	public boolean isCellEditable(int row, int column) {
        		return false;
        	};
        };  
        tableCustomerList.setModel(defaultTableModel);
        defaultTableModel.addColumn("Name");
        defaultTableModel.addColumn("Contact");
        defaultTableModel.addColumn("Code Customer");
        defaultTableModel.addColumn("Room");
        defaultTableModel.addColumn("Number Of Person");
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("JDBC:mysql://192.168.64.2:3306/Hotel_Management_System", "root", "password");
            Statement stmt = con.createStatement();
            stmt.executeUpdate("use Hotel_Management_System");
            ResultSet rs=stmt.executeQuery("SELECT * FROM bookings b JOIN customer c WHERE b.codeCustomer = c.codeCustomer AND b.checkout IS NULL");
            while(rs.next()){
                String name = rs.getString("name");
                String contact = rs.getString("contact");
                String code = rs.getString("codeCustomer");
                String room = rs.getString("room");
                String numberPersons = rs.getString("number_of_persons");
                
                defaultTableModel.addRow(new Object[]{name, contact, code, room, numberPersons});
            }
            rs.close();  
            con.close();
            stmt.close();           
        }
        catch(Exception e)
        {
            System.out.println("Esception: " + e);
        }
              
    }

    // ======== End Get Database Table Room ==========
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCustomerList = new javax.swing.JPanel();
        jScrollPaneCustomerList = new javax.swing.JScrollPane();
        tableCustomerList = new javax.swing.JTable();
        btnHome = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();
        btnCheckout.setText("Checkout");

        // frame
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCustomerList.setBackground(new java.awt.Color(255, 204, 204));
        
        lblCustomerList = new JLabel("Customer List");
        lblCustomerList.setBackground(Color.WHITE);
        lblCustomerList.setForeground(Color.WHITE);
        lblCustomerList.setFont(new Font("Lucida Grande", Font.BOLD | Font.ITALIC, 36));
        

        // Table
        tableCustomerList.setBackground(new java.awt.Color(255, 204, 204));
        jScrollPaneCustomerList.setViewportView(tableCustomerList);

        //Button Home
        btnHome.setFont(new Font("Dialog", Font.BOLD, 16)); 
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-home-page-32.png"))); 
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_buttonActionPerformed(evt);
            }
        });
        
       //Button Checkout
        btnCheckout.setFont(new Font("Dialog", Font.BOLD, 20));
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	checkout_buttonActionPerformed(evt);
            }
        });
      

        javax.swing.GroupLayout gl_jPanelCustomerList = new javax.swing.GroupLayout(jPanelCustomerList);
        gl_jPanelCustomerList.setHorizontalGroup(
        	gl_jPanelCustomerList.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanelCustomerList.createSequentialGroup()
        			.addContainerGap(433, Short.MAX_VALUE)
        			.addComponent(btnCheckout, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE)
        			.addGap(414))
        		.addGroup(gl_jPanelCustomerList.createSequentialGroup()
        			.addGap(82)
        			.addComponent(jScrollPaneCustomerList, GroupLayout.PREFERRED_SIZE, 845, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(79, Short.MAX_VALUE))
        		.addGroup(gl_jPanelCustomerList.createSequentialGroup()
        			.addComponent(btnHome, GroupLayout.PREFERRED_SIZE, 123, GroupLayout.PREFERRED_SIZE)
        			.addGap(241)
        			.addComponent(lblCustomerList, GroupLayout.PREFERRED_SIZE, 311, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(331, Short.MAX_VALUE))
        );
        gl_jPanelCustomerList.setVerticalGroup(
        	gl_jPanelCustomerList.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanelCustomerList.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_jPanelCustomerList.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblCustomerList, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnHome, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(jScrollPaneCustomerList, GroupLayout.PREFERRED_SIZE, 461, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
        			.addComponent(btnCheckout, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
        			.addGap(33))
        );
        jPanelCustomerList.setLayout(gl_jPanelCustomerList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCustomerList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCustomerList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    // ========= Begin Event Click Button ===========
    // Event home_buttonActionPerformed
    private void home_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        new MainScreen().setVisible(true);
        this.setVisible(false);
    }
    
    // Event checkout_buttonActionPerformed
    private void checkout_buttonActionPerformed(java.awt.event.ActionEvent evt) {
    	int row = tableCustomerList.getSelectedRow();
        String room = (String) tableCustomerList.getValueAt(row, 3);
        String code = (String) tableCustomerList.getValueAt(row, 2);
        

        Date time = java.util.Calendar.getInstance().getTime(); 
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("JDBC:mysql://192.168.64.2:3306/Hotel_Management_System", "root", "password");
            Statement stmt = con.createStatement();
            stmt.executeUpdate("USE Hotel_Management_System");
            ResultSet rs = stmt.executeQuery("SELECT * FROM bookings b JOIN customer c WHERE b.codeCustomer = c.codeCustomer AND b.checkout IS NULL AND b.codeCustomer = '" + code + "'");
            rs.next();
            String id = rs.getString("id");
            long surcharge = rs.getInt("surcharge");
            
            SimpleDateFormat format = new SimpleDateFormat("E MMMM dd HH:mm:ss z yyyy");
            
            Date check = format.parse(rs.getString("checkin"));
            long checkin = check.getTime();
            long checkout = time.getTime();
            long div = 1000 * 60 * 60 * 24;
            long days = (checkout - checkin) / div + 1;

            rs = stmt.executeQuery("SELECT * FROM room WHERE id = " + room);
            rs.next();
            int price = Integer.parseInt(rs.getString("price"));

            long bill = surcharge + price*days;
            
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Bill: " + bill, "Do you Want to Checkout?", dialogButton);
            if(dialogResult == 0) {
                stmt.executeUpdate("UPDATE room SET occupied = 0 WHERE id=" + room);
                stmt.executeUpdate("DELETE FROM bookfood WHERE room =" + room);
                stmt.executeUpdate("UPDATE bookings SET checkout='" + time + "' where id = " + id );
                JOptionPane.showMessageDialog(frame, "Checked Out");
                new CustomerList().setVisible(true);
                this.setVisible(false);
                con.close();
                stmt.close();          
            } 
            else{
                return;
            }             
        }
        catch(Exception e)
        {
            System.out.println("Esception: "+e);
        }
    }

    //========= End Event Click Button ===========

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnHome;
    private javax.swing.JPanel jPanelCustomerList;
    private javax.swing.JScrollPane jScrollPaneCustomerList;
    private javax.swing.JTable tableCustomerList;
    private JLabel lblCustomerList;
}
