/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package hotelmanagement;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import javax.swing.JLabel;
import java.awt.Color;

/**
 *
 * @author doanvanson
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
    	setTitle("Hotel Management - DVS");
        initComponents();
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        mainScreen = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnCustomerList = new javax.swing.JButton();
        btnRestaurant = new javax.swing.JButton();
        btnRoomsAvailable = new javax.swing.JButton();
        btnStaffInfo = new javax.swing.JButton();
        btnAddStaff = new javax.swing.JButton();

        // Frame
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        mainScreen.setBackground(new java.awt.Color(255, 204, 204));
        mainScreen.setForeground(new java.awt.Color(255, 204, 204));
        JLabel lblMainScreen = new JLabel("Main Screen");
        lblMainScreen.setForeground(Color.WHITE);
        lblMainScreen.setBackground(Color.WHITE);
        lblMainScreen.setFont(new Font("Lucida Grande", Font.BOLD | Font.ITALIC, 36));

        // Button Logout
        btnLogout.setFont(new Font("Dialog", Font.BOLD, 16)); 
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-exit-32.png"))); 
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        
        // Button Customer List
        btnCustomerList.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); 
        btnCustomerList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-people-64.png"))); 
        btnCustomerList.setText("Customer List");
        btnCustomerList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_buttonActionPerformed(evt);
            }
        });

        // Button Restaurant
        btnRestaurant.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); 
        btnRestaurant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-branding-64.png"))); 
        btnRestaurant.setText("Restaurant");
        btnRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurant_buttonActionPerformed(evt);
            }
        });

        // Button Rooms Available
        btnRoomsAvailable.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); 
        btnRoomsAvailable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-address-book-64.png"))); 
        btnRoomsAvailable.setText("Rooms Available");
        btnRoomsAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room_buttonActionPerformed(evt);
            }
        });

        //Button Staff Information
        btnStaffInfo.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); 
        btnStaffInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-supplier-64.png"))); 
        btnStaffInfo.setText("Staff Infomation");
        btnStaffInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_buttonActionPerformed(evt);
            }
        });

        //Button Add Staff
        btnAddStaff.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnAddStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-name-tag-64.png"))); // NOI18N
        btnAddStaff.setText("Add Staff");
        btnAddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_staff_buttonActionPerformed(evt);
            }
        });
        
        

        
        
        javax.swing.GroupLayout gl_mainScreen = new javax.swing.GroupLayout(mainScreen);
        gl_mainScreen.setHorizontalGroup(
        	gl_mainScreen.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_mainScreen.createSequentialGroup()
        			.addContainerGap(476, Short.MAX_VALUE)
        			.addComponent(btnAddStaff, GroupLayout.PREFERRED_SIZE, 356, GroupLayout.PREFERRED_SIZE)
        			.addGap(448))
        		.addGroup(gl_mainScreen.createSequentialGroup()
        			.addGap(92)
        			.addGroup(gl_mainScreen.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(btnStaffInfo, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(btnRoomsAvailable, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
        			.addGap(162)
        			.addGroup(gl_mainScreen.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(btnRestaurant, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(btnCustomerList, GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
        			.addContainerGap(123, Short.MAX_VALUE))
        		.addGroup(gl_mainScreen.createSequentialGroup()
        			.addGap(536)
        			.addComponent(lblMainScreen, GroupLayout.PREFERRED_SIZE, 316, GroupLayout.PREFERRED_SIZE)
        			.addGap(289)
        			.addComponent(btnLogout, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        gl_mainScreen.setVerticalGroup(
        	gl_mainScreen.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_mainScreen.createSequentialGroup()
        			.addGroup(gl_mainScreen.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_mainScreen.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(btnLogout, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE))
        				.addGroup(gl_mainScreen.createSequentialGroup()
        					.addGap(31)
        					.addComponent(lblMainScreen, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)))
        			.addGap(32)
        			.addGroup(gl_mainScreen.createParallelGroup(Alignment.LEADING)
        				.addComponent(btnCustomerList, GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        				.addComponent(btnRoomsAvailable, GroupLayout.PREFERRED_SIZE, 215, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(gl_mainScreen.createParallelGroup(Alignment.LEADING)
        				.addComponent(btnStaffInfo, GroupLayout.PREFERRED_SIZE, 228, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnRestaurant, GroupLayout.PREFERRED_SIZE, 222, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(btnAddStaff, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE)
        			.addGap(47))
        );
        mainScreen.setLayout(gl_mainScreen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(mainScreen, GroupLayout.PREFERRED_SIZE, 1280, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(mainScreen, GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>

    
    // ========= Begin Event Click Button ===========
    
    // Event room_buttonActionPerformed
    private void room_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        new RoomAvailable().setVisible(true);
        this.setVisible(false);
    }
    
    // Event customer_buttonActionPerformed
    private void customer_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        new CustomerList().setVisible(true);
        this.setVisible(false);
    }

    // Event staff_buttonActionPerformed
    private void staff_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        new StaffInfo().setVisible(true);
        this.setVisible(false);
    }

    // Event rest_buttonActionPerformed
    private void restaurant_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        new Restaurant().setVisible(true);
        this.setVisible(false);
    }
    
    // Event add_staff_buttonActionPerformed
    private void add_staff_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        new AddStaff().setVisible(true);
        this.setVisible(false);
    }

    // Event logout_buttonActionPerformed
    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        new Login().setVisible(true);
        this.setVisible(false);
    }
    
    //========= End Event Click Button ===========
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JButton btnAddStaff;
    private javax.swing.JButton btnCustomerList;
    private javax.swing.JPanel mainScreen;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRestaurant;
    private javax.swing.JButton btnRoomsAvailable;
    private javax.swing.JButton btnStaffInfo;
}