/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package hotelmanagement;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import java.awt.Font;
import java.awt.Color;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author doanvanson
 */
public class RemoveItem extends javax.swing.JFrame {

    /**
     * Creates new form RemoveItem
     */
    public RemoveItem() {
    	setTitle("Hotel Management - DVS");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        removeItem = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        lblItemName = new javax.swing.JLabel();
        lblItemName.setFont(new Font("Lucida Grande", Font.PLAIN, 16));
        inputItemName = new javax.swing.JTextField();
        btnRemoveItem = new javax.swing.JButton();

        //Frame
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        removeItem.setBackground(new java.awt.Color(255, 204, 204));

        lblRemoveItem = new JLabel("Remove Item");
        lblRemoveItem.setBackground(Color.WHITE);
        lblRemoveItem.setForeground(Color.WHITE);
        lblRemoveItem.setFont(new Font("Lucida Grande", Font.BOLD | Font.ITALIC, 36));
        
        //lbl Content
        lblItemName.setText("Item Name");

        // Button Back
        btnBack.setFont(new Font("Dialog", Font.BOLD, 16)); 
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-go-back-32.png"))); 
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        // Button Remove
        btnRemoveItem.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); 
        btnRemoveItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-fallen-ice-cream-cone-64.png"))); 
        btnRemoveItem.setText("Remove Item");
        btnRemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_buttonActionPerformed(evt);
            }
        });
        

        javax.swing.GroupLayout gl_removeItem = new javax.swing.GroupLayout(removeItem);
        gl_removeItem.setHorizontalGroup(
        	gl_removeItem.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_removeItem.createSequentialGroup()
        			.addContainerGap(209, Short.MAX_VALUE)
        			.addGroup(gl_removeItem.createParallelGroup(Alignment.TRAILING)
        				.addComponent(lblRemoveItem, GroupLayout.PREFERRED_SIZE, 275, GroupLayout.PREFERRED_SIZE)
        				.addGroup(gl_removeItem.createSequentialGroup()
        					.addComponent(lblItemName)
        					.addGap(35)
        					.addComponent(inputItemName, GroupLayout.PREFERRED_SIZE, 172, GroupLayout.PREFERRED_SIZE)))
        			.addGap(81)
        			.addComponent(btnBack, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE))
        		.addGroup(gl_removeItem.createSequentialGroup()
        			.addGap(227)
        			.addComponent(btnRemoveItem)
        			.addContainerGap(229, Short.MAX_VALUE))
        );
        gl_removeItem.setVerticalGroup(
        	gl_removeItem.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_removeItem.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_removeItem.createParallelGroup(Alignment.TRAILING)
        				.addGroup(gl_removeItem.createSequentialGroup()
        					.addComponent(lblRemoveItem, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
        					.addGroup(gl_removeItem.createParallelGroup(Alignment.BASELINE)
        						.addComponent(inputItemName, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblItemName))
        					.addContainerGap(191, Short.MAX_VALUE))
        				.addGroup(gl_removeItem.createSequentialGroup()
        					.addComponent(btnBack, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
        					.addComponent(btnRemoveItem)
        					.addGap(50))))
        );
        removeItem.setLayout(gl_removeItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removeItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removeItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    // ========= Begin Event Click Button ===========
    
    // Event remove_buttonActionPerformed
    private void remove_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        String nameItem = inputItemName.getText();
        
        if(nameItem.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill the details");
            return;
        }
        try{
        	Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("JDBC:mysql://192.168.64.2:3306/Hotel_Management_System","root","password");
            Statement stmt = con.createStatement();
            stmt.executeUpdate("USE Hotel_Management_System");
            
            ResultSet rs = stmt.executeQuery("SELECT * FROM itemRestaurant");
            int flagCheckItemnName =0;
            while(rs.next()){
                String itemName = rs.getString("itemName");
                if(nameItem.equals(itemName)){
                	flagCheckItemnName = 1;
                    break;
                }
            }
            if(flagCheckItemnName == 0) 
                    JOptionPane.showMessageDialog(null, "Food Item not available");
            rs.close();
            
            if(flagCheckItemnName == 1){
                stmt.executeUpdate("DELETE FROM itemRestaurant WHERE itemName ='" + nameItem + "'");
                JOptionPane.showMessageDialog(null, "Item Removed");
                new Restaurant().setVisible(true);
                this.setVisible(false);
            }
            else inputItemName.setText("");
        }
        catch(  HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e)
        {
            System.out.println("Esception: "+e);
        }
        
    }

    // Event back_buttonActionPerformed
    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        new Restaurant().setVisible(true);
        this.setVisible(false);
    }
    
    
    //========= End Event Click Button ===========
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField inputItemName;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JPanel removeItem;
    private javax.swing.JButton btnRemoveItem;
    private JLabel lblRemoveItem;
    // End of variables declaration//GEN-END:variables
}