/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package hotelmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Font;

/**
 *
 * @author doanvanson
 */
public class RoomAvailable extends javax.swing.JFrame {

    /**
     * Creates new form RoomList
     */
    public RoomAvailable() {
    	setTitle("Hotel Management - DVS");
        initComponents();
        showDetails();
    }
    
    // ======== Begin Get Database Table Room ========== 
    public void showDetails(){
        DefaultTableModel defaultTableModel = new DefaultTableModel(){
        	@Override
        	public boolean isCellEditable(int row, int column) {
        		return false;
        	};
        };
        tableRoomsAvailable.setModel(defaultTableModel); 
        
        defaultTableModel.addColumn("ID");
        defaultTableModel.addColumn("Beds");
        defaultTableModel.addColumn("Capacity");
        defaultTableModel.addColumn("Price");
        
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("JDBC:mysql://192.168.64.2:3306/Hotel_Management_System","root","password");
            Statement stmt = con.createStatement();
            stmt.executeUpdate("USE Hotel_Management_System");
            ResultSet rs = stmt.executeQuery("SELECT * FROM room WHERE occupied = 0");
            
            while(rs.next()){
                String id = rs.getString("id");
                String beds = rs.getString("beds");
                String capacity = rs.getString("capacity");
                String price = rs.getString("price");
                
                defaultTableModel.addRow(new Object[]{id,beds,capacity,price});
            }
            
            rs.close();  
            con.close();
            stmt.close();           
        }
        catch(Exception e)
        {
            System.out.println("Esception: " + e);
        }
    	
               
    }

    // ======== End Get Database Table Room ==========
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        roomsAvailable = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        jScrollPaneRoomsAvailable = new javax.swing.JScrollPane();
        tableRoomsAvailable = new javax.swing.JTable();
        tableRoomsAvailable.setForeground(Color.BLACK);
        btnBooking = new javax.swing.JButton();

        // Frame
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        roomsAvailable.setBackground(new java.awt.Color(255, 204, 204));
        lblRoomAvailable = new JLabel("Rooms Available");
        lblRoomAvailable.setForeground(Color.WHITE);
        lblRoomAvailable.setBackground(Color.WHITE);
        lblRoomAvailable.setFont(new Font("Lucida Grande", Font.BOLD | Font.ITALIC, 36));


        // Button Home
        btnHome.setFont(new Font("Dialog", Font.BOLD, 14)); 
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-home-page-32.png"))); 
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_buttonActionPerformed(evt);
            }
        });

        
        // Table Rooms Available
        tableRoomsAvailable.setBackground(new Color(255, 204, 204));
        jScrollPaneRoomsAvailable.setViewportView(tableRoomsAvailable);

        // Button Booking Room
        btnBooking.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); 
        btnBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-bed-64.png")));
        btnBooking.setText("Book Room");
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });
        
       
        javax.swing.GroupLayout gl_roomsAvailable = new javax.swing.GroupLayout(roomsAvailable);
        gl_roomsAvailable.setHorizontalGroup(
        	gl_roomsAvailable.createParallelGroup(Alignment.TRAILING)
        		.addGroup(gl_roomsAvailable.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(btnHome, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE)
        			.addGap(226)
        			.addComponent(lblRoomAvailable, GroupLayout.PREFERRED_SIZE, 355, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(303, Short.MAX_VALUE))
        		.addGroup(gl_roomsAvailable.createSequentialGroup()
        			.addGap(405)
        			.addComponent(btnBooking)
        			.addContainerGap(385, Short.MAX_VALUE))
        		.addGroup(gl_roomsAvailable.createSequentialGroup()
        			.addContainerGap(86, Short.MAX_VALUE)
        			.addComponent(jScrollPaneRoomsAvailable, GroupLayout.PREFERRED_SIZE, 847, GroupLayout.PREFERRED_SIZE)
        			.addGap(79))
        );
        gl_roomsAvailable.setVerticalGroup(
        	gl_roomsAvailable.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_roomsAvailable.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_roomsAvailable.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblRoomAvailable, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnHome, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(jScrollPaneRoomsAvailable, GroupLayout.PREFERRED_SIZE, 451, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(btnBooking)
        			.addGap(22))
        );
        roomsAvailable.setLayout(gl_roomsAvailable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomsAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomsAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    
    // ========= Begin Event Click Button ===========
    
    // Event home_buttonActionPerformed
    private void home_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        new MainScreen().setVisible(true);
        this.setVisible(false);
    }
    
    //Event bookButtonActionPerformed
    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {
        new BookingRoom().setVisible(true);
        this.setVisible(false);
    }

    //========= End Event Click Button ===========
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomAvailable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomAvailable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomAvailable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomAvailable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomAvailable().setVisible(true);
            }
        });
    }
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton btnHome;
    private javax.swing.JPanel roomsAvailable;
    private javax.swing.JScrollPane jScrollPaneRoomsAvailable;
    private javax.swing.JTable tableRoomsAvailable;
    private JLabel lblRoomAvailable;
    // End of variables declaration
}
